language: python
python:
    - 2.7
    - 3.2
    - 3.5

services:
    - docker

install:
    - docker run dflima/whale

script:
    - docker ps -a | grep dflima/docker-whale

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push dflima/docker-whale;
      fi
